In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/covid_toy.csv")

In [105]:
df.head()

   age  gender cough     city has_covid  fever
0   60    Male  Mild  Kolkata        No  103.0
1   27    Male  Mild    Delhi       Yes  100.0
2   42    Male  Mild    Delhi        No  101.0
3   31  Female  Mild  Kolkata        No   98.0
4   65  Female  Mild   Mumbai        No  101.0

In [ ]:
from sklearn.impute import SimpleImputer
SI=SimpleImputer();
fever=SI.fit_transform(df[['fever']])

In [69]:
df.drop('fever',axis=1,inplace=True)

In [70]:
fever=pd.DataFrame(fever,columns=['fever'])

In [71]:
df['fever']=fever

In [72]:
df.head()

   age  gender cough     city has_covid  fever
0   60    Male  Mild  Kolkata        No  103.0
1   27    Male  Mild    Delhi       Yes  100.0
2   42    Male  Mild    Delhi        No  101.0
3   31  Female  Mild  Kolkata        No   98.0
4   65  Female  Mild   Mumbai        No  101.0

In [81]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df.drop(['age','fever','has_covid'],axis=1),df['has_covid'])

In [74]:
# gender and city -> One Hot Encoding bz it is Nominal Column
# cough -> Ordinal Encoding because it is Ordinal Column

In [75]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import(
    OneHotEncoder,
    OrdinalEncoder
)

In [82]:
from pandas.core.arrays import sparse
transformer=ColumnTransformer(transformers=[
    ('trf1',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('trf2',OneHotEncoder(sparse_output=False,drop='first',),['gender','city'])
])

In [83]:
X_train

    gender   cough       city
49    Male    Mild     Mumbai
57  Female  Strong  Bangalore
86    Male    Mild  Bangalore
55  Female    Mild     Mumbai
14    Male    Mild  Bangalore
..     ...     ...        ...
80  Female    Mild     Mumbai
50    Male    Mild      Delhi
12  Female  Strong    Kolkata
42    Male    Mild      Delhi
92  Female  Strong    Kolkata

[75 rows x 3 columns]

In [100]:
New=transformer.fit_transform(X_train).astype(np.int8)

In [101]:
New=pd.DataFrame(New,columns=transformer.get_feature_names_out())

In [106]:
New['age']=df['age']
New['fever']=df['fever']

In [107]:
New

,trf1__cough,trf2__gender_Male,trf2__city_Delhi,trf2__city_Kolkata,trf2__city_Mumbai,age,fever
0,0,1,0,0,1,60,103.0
1,1,0,0,0,0,27,100.0
2,0,1,0,0,0,42,101.0
3,0,0,0,0,1,31,98.0
4,0,1,0,0,0,65,101.0
...,...,...,...,...,...,...,...
70,0,0,0,0,1,68,101.0
71,0,1,1,0,0,75,104.0
72,1,0,0,1,0,83,101.0
73,0,1,1,0,0,34,98.0
74,1,0,0,1,0,34,104.0